# Generated by Django 4.0.6 on 2022-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_logs_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ticket',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
