# Generated by Django 4.0.6 on 2022-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_logs_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('ticket', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('status_aberto', models.BooleanField(default=True)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
