# Generated by Django 4.0.6 on 2022-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_solicitacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='impressora',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='marca',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='setor',
            field=models.CharField(default='2022-07-12 13:00:00', max_length=100),
            preserve_default=False,
        ),
    ]
