# Generated by Django 4.0.6 on 2022-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_setor_solicitacoes_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='encerrado_por',
            field=models.CharField(default='Kaio', max_length=100),
            preserve_default=False,
        ),
    ]
