# Generated by Django 4.0.6 on 2022-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_solicitacoes_encerrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='encerrado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
