# Generated by Django 4.0.6 on 2022-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_solicitacoes_encerrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='encerrado_em',
            field=models.DateTimeField(default='2022-10-20 00:00'),
            preserve_default=False,
        ),
    ]
