# Generated by Django 4.0.6 on 2022-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_solicitacoes_encerrado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='encerrado_em',
            field=models.DateTimeField(blank=True),
        ),
    ]
